#!/bin/bash
# To resolve SECSCN test L2.4
# Description:
#  Critical File Permissions
#  Verify permissions are not more permissible than the expected results 
#  for system critical files (if exits) 

/bin/chmod 0444 /etc/.login
/bin/chmod 0444 /etc/X11/Xservers
/bin/chmod 0644 /etc/X11/gdm/gdm.conf
/bin/chmod 0644 /etc/X11/xdm/Xresources
/bin/chmod 0644 /etc/X11/xdm/kdmrc
/bin/chmod 0755 /etc/X11/xinit/xserverrc
/bin/chmod 0644 /etc/aliases
/bin/chmod 0644 /etc/anacrontab
/bin/chmod 0400 /etc/at.allow
/bin/chmod 0600 /etc/at.deny
/bin/chmod 0600 /etc/audit.rules
/bin/chmod 0600 /etc/audit/audit.rules
/bin/chmod 0600 /etc/audit/auditd.conf
/bin/chmod 0600 /etc/auditd.conf
/bin/chmod 0644 /etc/auto.master
/bin/chmod 0644 /etc/auto.misc
/bin/chmod 0444 /etc/bashrc
/bin/chmod 0400 /etc/cron.allow
/bin/chmod 0600 /etc/cron.d/at.allow
/bin/chmod 0600 /etc/cron.d/at.deny
/bin/chmod 0600 /etc/cron.d/cron.allow
/bin/chmod 0600 /etc/cron.d/cron.deny
/bin/chmod 0600 /etc/cron.deny
/bin/chmod 0400 /etc/crontab
/bin/chmod 0444 /etc/csh.cshrc
/bin/chmod 0444 /etc/csh.login
/bin/chmod 0600 /etc/cups/client.conf
/bin/chmod 0600 /etc/cups/cupsd.conf
/bin/chmod 0644 /etc/defaultdomain
/bin/chmod 0644 /etc/defaultrouter
/bin/chmod 0644 /etc/dhclient-eth0.conf
/bin/chmod 0644 /etc/dhcpd.conf
/bin/chmod 0644 /etc/dt/config/Xaccess
/bin/chmod 0644 /etc/exports
/bin/chmod 0644 /etc/firmware/microcode.dat
/bin/chmod 0644 /etc/fstab
/bin/chmod 0600 /etc/ftpd/ftpusers
/bin/chmod 0600 /etc/ftpusers
/bin/chmod 0644 /etc/group
/bin/chmod 0600 /etc/grub.conf
/bin/chmod 0600 /etc/grub/grub.conf
/bin/chmod 0400 /etc/gshadow
/bin/chmod 0644 /etc/host.conf
/bin/chmod 0444 /etc/hosts
/bin/chmod 0644 /etc/hosts.allow
/bin/chmod 0644 /etc/hosts.deny
/bin/chmod 0000 /etc/hosts.equiv
/bin/chmod 0444 /etc/inetd.conf
/bin/chmod 0744 /etc/init.d/inetsvc
/bin/chmod 0644 /etc/initlog.conf
/bin/chmod 0600 /etc/inittab
/bin/chmod 0644 /etc/issue
/bin/chmod 0644 /etc/issue.net
/bin/chmod 0644 /etc/krb.conf
/bin/chmod 0644 /etc/krb.realms
/bin/chmod 0644 /etc/krb5.conf
/bin/chmod 0644 /etc/ld.so.conf
/bin/chmod 0644 /etc/ldap.conf
/bin/chmod 0600 /etc/lilo.conf
/bin/chmod 0644 /etc/localtime
/bin/chmod 0640 /etc/login.defs
/bin/chmod 0644 /etc/mail/Makefile
/bin/chmod 0644 /etc/mail/access
/bin/chmod 0640 /etc/mail/access.db
/bin/chmod 0644 /etc/mail/aliases
/bin/chmod 0644 /etc/mail/domaintable
/bin/chmod 0640 /etc/mail/domaintable.db
/bin/chmod 0644 /etc/mail/helpfile
/bin/chmod 0644 /etc/mail/local-host-names
/bin/chmod 0644 /etc/mail/mailertable
/bin/chmod 0640 /etc/mail/mailertable.db
/bin/chmod 0444 /etc/mail/sendmail.cf
/bin/chmod 0644 /etc/mail/sendmail.mc
/bin/chmod 0444 /etc/mail/submit.cf
/bin/chmod 0644 /etc/mail/submit.mc
/bin/chmod 0644 /etc/mail/trusted-users
/bin/chmod 0644 /etc/mail/virtusertable
/bin/chmod 0640 /etc/mail/virtusertable.db
/bin/chmod 0644 /etc/microcode.dat
/bin/chmod 0644 /etc/modprobe.conf
/bin/chmod 0644 /etc/motd
/bin/chmod 0644 /etc/my.conf
/bin/chmod 0644 /etc/netconfig
/bin/chmod 0444 /etc/netmasks
/bin/chmod 0444 /etc/networks
/bin/chmod 0644 /etc/nsswitch.conf
/bin/chmod 0600 /etc/ntp.conf
/bin/chmod 0600 /etc/ntp.keys
/bin/chmod 0644 /etc/pam.conf
/bin/chmod 0755 /etc/pam.d
/bin/chmod 0644 /etc/pam.d/*
/bin/chmod 0644 /etc/pam.d/su
/bin/chmod 0644 /etc/pam.d/system-auth
/bin/chmod 0644 /etc/pam_smb.conf
/bin/chmod 0644 /etc/passwd
/bin/chmod 0444 /etc/profile
/bin/chmod 0744 /etc/rc.d/init.d/auditd
/bin/chmod 0755 /etc/rc.d/rc.local
/bin/chmod 0755 /etc/rc.d/rc.sysinit
/bin/chmod 0755 /etc/rc.local
/bin/chmod 0755 /etc/rc.sysinit
/bin/chmod 0644 /etc/resolv.conf
/bin/chmod 0644 /etc/samba/secrets.tdb
/bin/chmod 0644 /etc/samba/smb.conf
/bin/chmod 0644 /etc/samba/smbpasswd
/bin/chmod 0400 /etc/securetty
/bin/chmod 0640 /etc/security/access.conf
/bin/chmod 0600 /etc/security/console.perms
/bin/chmod 0600 /etc/security/console.perms.d/50-default.perms
/bin/chmod 0600 /etc/security/limits
/bin/chmod 0600 /etc/security/opasswd
/bin/chmod 0444 /etc/services
/bin/chmod 0400 /etc/shadow
/bin/chmod 0400 /etc/shadow.OLD
/bin/chmod 0444 /etc/shells
/bin/chmod 0600 /etc/skel/.bashrc
/bin/chmod 0644 /etc/skel/local.cshrc
/bin/chmod 0644 /etc/skel/local.login
/bin/chmod 0644 /etc/skel/local.profile
/bin/chmod 0644 /etc/snmp/snmpd.conf
/bin/chmod 0600 /etc/ssh/sshd_config
/bin/chmod 0640 /etc/stunnel/stunnel.conf
/bin/chmod 0640 /etc/stunnel/stunnel.pem
/bin/chmod 0440 /etc/sudoers
/bin/chmod 0755 /etc/sysconfig/
/bin/chmod 0755 /etc/sysconfig/init
/bin/chmod 0644 /etc/sysconfig/sendmail
/bin/chmod 0600 /etc/sysctl.conf
/bin/chmod 0600 /etc/syslog.conf
/bin/chmod 0600 /etc/vsftpd.conf
/bin/chmod 0600 /etc/vsftpd/ftpusers
/bin/chmod 0600 /etc/vsftpd/vsftpd.conf
/bin/chmod 0644 /etc/xinetd.conf
/bin/chmod 0644 /etc/xinetd.d/wu-ftpd
/bin/chmod 0644 /etc/yp.conf
/bin/chmod 0600 /root/.ICEauthority
/bin/chmod 0600 /root/.Xauthority
/bin/chmod 0600 /root/.Xdefaults
/bin/chmod 0600 /root/.bash_history
/bin/chmod 0600 /root/.bash_logout
/bin/chmod 0400 /root/.bash_profile
/bin/chmod 0400 /root/.bashrc
/bin/chmod 0400 /root/.cshrc
/bin/chmod 0600 /root/.gtkrc
/bin/chmod 0600 /root/.login
/bin/chmod 0000 /root/.netrc
/bin/chmod 0600 /root/.profile
/bin/chmod 0000 /root/.rhosts
/bin/chmod 0000 /root/.shosts
/bin/chmod 0400 /root/.tcshrc
/bin/chmod 4755 /usr/bin/lppasswd
/bin/chmod 0755 /usr/bin/lpq*
/bin/chmod 0755 /usr/bin/lpr*
/bin/chmod 0755 /usr/bin/lprm*
/bin/chmod 0755 /usr/bin/lpstat*
/bin/chmod 0550 /usr/sbin/swap
/bin/chmod 0600 /var/log/audit/audit_log
/bin/chmod 0600 /var/log/audit/audit_log.1
/bin/chmod 0600 /var/log/audit/audit_log.2
/bin/chmod 0600 /var/log/audit/audit_log.3
/bin/chmod 0600 /var/log/audit/audit_log.4
/bin/chmod 0600 /var/log/authlog
/bin/chmod 0600 /var/log/boot.log*
/bin/chmod 0600 /var/log/btmp
/bin/chmod 0600 /var/log/cron*
/bin/chmod 0600 /var/log/dmesg
/bin/chmod 0600 /var/log/faillog
/bin/chmod 0600 /var/log/httpd/*
/bin/chmod 0600 /var/log/ksyms*
/bin/chmod 0400 /var/log/lastlog
/bin/chmod 0600 /var/log/loginlog
/bin/chmod 0600 /var/log/maillog*
/bin/chmod 0600 /var/log/messages
/bin/chmod 0600 /var/log/messages*
/bin/chmod 0600 /var/log/news/*
/bin/chmod 0600 /var/log/pgsql
/bin/chmod 0600 /var/log/rpmpkgs*
/bin/chmod 0600 /var/log/sa/*
/bin/chmod 0600 /var/log/samba/*
/bin/chmod 0600 /var/log/scrollkeeper.log
/bin/chmod 0600 /var/log/secure
/bin/chmod 0600 /var/log/secure*
/bin/chmod 0600 /var/log/spooler*
/bin/chmod 0600 /var/log/squid/*
/bin/chmod 0600 /var/log/sulog
/bin/chmod 0600 /var/log/syslog
/bin/chmod 0600 /var/log/vbox/*
/bin/chmod 0600 /var/log/wtmp
/bin/chmod 0700 /var/spool/at
/bin/chmod 0700 /var/spool/cron
/bin/chmod 0600 /var/spool/cron/root
/bin/chmod 0600 /var/yp/binding
/bin/chown root:root /etc/.login  
/bin/chown root:root /etc/X11/Xservers  
/bin/chown root:root /etc/X11/gdm/gdm.conf  
/bin/chown root:root /etc/X11/xdm/Xresources  
/bin/chown root:root /etc/X11/xdm/kdmrc  
/bin/chown root:root /etc/X11/xinit/xserverrc  
/bin/chown root:root /etc/aliases  
/bin/chown root:root /etc/anacrontab  
/bin/chown root:root /etc/at.allow  
/bin/chown root:root /etc/at.deny  
/bin/chown root:root /etc/audit.rules  
/bin/chown root:root /etc/audit/audit.rules  
/bin/chown root:root /etc/audit/auditd.conf  
/bin/chown root:root /etc/auditd.conf  
/bin/chown root:root /etc/auto.master  
/bin/chown root:root /etc/auto.misc  
/bin/chown root:root /etc/bashrc  
/bin/chown root:root /etc/cron.allow  
/bin/chown root:root /etc/cron.d/at.allow  
/bin/chown root:root /etc/cron.d/at.deny  
/bin/chown root:root /etc/cron.d/cron.allow  
/bin/chown root:root /etc/cron.d/cron.deny  
/bin/chown root:root /etc/cron.deny  
/bin/chown root:root /etc/crontab  
/bin/chown root:root /etc/csh.cshrc  
/bin/chown root:root /etc/csh.login  
/bin/chown lp:sys /etc/cups/client.conf  
/bin/chown lp:sys /etc/cups/cupsd.conf  
/bin/chown root:root /etc/defaultdomain  
/bin/chown root:root /etc/defaultrouter  
/bin/chown root:root /etc/dhclient-eth0.conf  
/bin/chown root:root /etc/dhcpd.conf  
/bin/chown root:root /etc/dt/config/Xaccess  
/bin/chown root:root /etc/exports  
/bin/chown root:root /etc/firmware/microcode.dat  
/bin/chown root:root /etc/fstab  
/bin/chown root:root /etc/ftpd/ftpusers  
/bin/chown root:root /etc/ftpusers  
/bin/chown root:root /etc/group  
/bin/chown root:root /etc/grub.conf  
/bin/chown root:root /etc/grub/grub.conf  
/bin/chown root:root /etc/gshadow  
/bin/chown root:root /etc/host.conf  
/bin/chown root:root /etc/hosts  
/bin/chown root:root /etc/hosts.allow  
/bin/chown root:root /etc/hosts.deny  
/bin/chown root:root /etc/hosts.equiv  
/bin/chown root:root /etc/inetd.conf  
/bin/chown root:root /etc/init.d/inetsvc  
/bin/chown root:root /etc/initlog.conf  
/bin/chown root:root /etc/inittab  
/bin/chown root:root /etc/issue  
/bin/chown root:root /etc/issue.net  
/bin/chown root:root /etc/krb.conf  
/bin/chown root:root /etc/krb.realms  
/bin/chown root:root /etc/krb5.conf  
/bin/chown root:root /etc/ld.so.conf  
/bin/chown root:root /etc/ldap.conf  
/bin/chown root:root /etc/lilo.conf  
/bin/chown root:root /etc/localtime  
/bin/chown root:root /etc/login.defs  
/bin/chown root:root /etc/mail/Makefile  
/bin/chown root:root /etc/mail/access  
/bin/chown root:root /etc/mail/access.db  
/bin/chown root:root /etc/mail/aliases  
/bin/chown root:root /etc/mail/domaintable  
/bin/chown root:root /etc/mail/domaintable.db  
/bin/chown root:root /etc/mail/helpfile  
/bin/chown root:root /etc/mail/local-host-names  
/bin/chown root:root /etc/mail/mailertable  
/bin/chown root:root /etc/mail/mailertable.db  
/bin/chown root:bin /etc/mail/sendmail.cf  
/bin/chown root:root /etc/mail/sendmail.mc  
/bin/chown root:root /etc/mail/submit.cf  
/bin/chown root:root /etc/mail/submit.mc  
/bin/chown root:root /etc/mail/trusted-users  
/bin/chown root:root /etc/mail/virtusertable  
/bin/chown root:root /etc/mail/virtusertable.db  
/bin/chown root:root /etc/microcode.dat  
/bin/chown root:root /etc/modprobe.conf  
/bin/chown root:root /etc/motd  
/bin/chown root:root /etc/my.conf  
/bin/chown root:root /etc/netconfig  
/bin/chown root:root /etc/netmasks  
/bin/chown root:root /etc/networks  
/bin/chown root:root /etc/nsswitch.conf  
/bin/chown root:root /etc/ntp.conf  
/bin/chown root:root /etc/ntp.keys  
/bin/chown root:root /etc/pam.conf  
/bin/chown root:root /etc/pam.d  
/bin/chown root:root /etc/pam.d/*  
/bin/chown root:root /etc/pam.d/su  
/bin/chown root:root /etc/pam.d/system-auth  
/bin/chown root:root /etc/pam_smb.conf  
/bin/chown root:root /etc/passwd  
/bin/chown root:root /etc/profile  
/bin/chown root:root /etc/rc.d/init.d/auditd  
/bin/chown root:root /etc/rc.d/rc.local  
/bin/chown root:root /etc/rc.d/rc.sysinit  
/bin/chown root:root /etc/rc.local  
/bin/chown root:root /etc/rc.sysinit  
/bin/chown root:root /etc/resolv.conf  
/bin/chown root:root /etc/samba/secrets.tdb  
/bin/chown root:root /etc/samba/smb.conf  
/bin/chown root:root /etc/samba/smbpasswd  
/bin/chown root:root /etc/securetty  
/bin/chown root:root /etc/security/access.conf  
/bin/chown root:root /etc/security/console.perms  
/bin/chown root:root /etc/security/console.perms.d/50-default.perms  
/bin/chown root:root /etc/security/limits  
/bin/chown root:root /etc/security/opasswd  
/bin/chown root:root /etc/services  
/bin/chown root:root /etc/shadow  
/bin/chown root:root /etc/shadow.OLD  
/bin/chown root:root /etc/shells  
/bin/chown root:root /etc/skel/.bashrc  
/bin/chown root:root /etc/skel/local.cshrc  
/bin/chown root:root /etc/skel/local.login  
/bin/chown root:root /etc/skel/local.profile  
/bin/chown root:root /etc/snmp/snmpd.conf  
/bin/chown root:root /etc/ssh/sshd_config  
/bin/chown root:root /etc/stunnel/stunnel.conf  
/bin/chown root:root /etc/stunnel/stunnel.pem  
/bin/chown root:root /etc/sudoers  
/bin/chown root:root /etc/sysconfig/  
/bin/chown root:root /etc/sysconfig/init  
/bin/chown root:root /etc/sysconfig/sendmail  
/bin/chown root:root /etc/sysctl.conf  
/bin/chown root:root /etc/syslog.conf  
/bin/chown root:root /etc/vsftpd.conf  
/bin/chown root:root /etc/vsftpd/ftpusers  
/bin/chown root:root /etc/vsftpd/vsftpd.conf  
/bin/chown root:root /etc/xinetd.conf  
/bin/chown root:root /etc/xinetd.d/wu-ftpd  
/bin/chown root:root /etc/yp.conf  
/bin/chown root:root /root/.ICEauthority  
/bin/chown root:root /root/.Xauthority  
/bin/chown root:root /root/.Xdefaults  
/bin/chown root:root /root/.bash_history  
/bin/chown root:root /root/.bash_logout  
/bin/chown root:root /root/.bash_profile  
/bin/chown root:root /root/.bashrc  
/bin/chown root:root /root/.cshrc  
/bin/chown root:root /root/.gtkrc  
/bin/chown root:root /root/.login  
/bin/chown root:root /root/.netrc  
/bin/chown root:root /root/.profile  
/bin/chown root:root /root/.rhosts  
/bin/chown root:root /root/.shosts  
/bin/chown root:root /root/.tcshrc  
/bin/chown root:root /usr/bin/lppasswd  
/bin/chown root:root /usr/bin/lpq*  
/bin/chown root:root /usr/bin/lpr*  
/bin/chown root:root /usr/bin/lprm*  
/bin/chown root:root /usr/bin/lpstat*  
/bin/chown root:bin /usr/sbin/swap  
/bin/chown root:root /var/log/audit/audit_log  
/bin/chown root:root /var/log/audit/audit_log.1  
/bin/chown root:root /var/log/audit/audit_log.2  
/bin/chown root:root /var/log/audit/audit_log.3  
/bin/chown root:root /var/log/audit/audit_log.4  
/bin/chown root:root /var/log/authlog  
/bin/chown root:root /var/log/boot.log*  
/bin/chown root:root /var/log/btmp  
/bin/chown root:root /var/log/cron*  
/bin/chown root:root /var/log/dmesg  
/bin/chown root:root /var/log/faillog  
/bin/chown root:root /var/log/httpd/*  
/bin/chown root:root /var/log/ksyms*  
/bin/chown root:root /var/log/lastlog  
/bin/chown root:root /var/log/loginlog  
/bin/chown root:root /var/log/maillog*  
/bin/chown root:root /var/log/messages  
/bin/chown root:root /var/log/messages*  
/bin/chown news:news /var/log/news/*  
/bin/chown postgres:postgres /var/log/pgsql  
/bin/chown root:root /var/log/rpmpkgs*  
/bin/chown root:root /var/log/sa/*  
/bin/chown root:root /var/log/samba/*  
/bin/chown root:root /var/log/scrollkeeper.log  
/bin/chown root:root /var/log/secure  
/bin/chown root:root /var/log/secure*  
/bin/chown root:root /var/log/spooler*  
/bin/chown squid:squid /var/log/squid/*  
/bin/chown root:root /var/log/sulog  
/bin/chown root:root /var/log/syslog  
/bin/chown root:root /var/log/vbox/*  
/bin/chown root:root /var/log/wtmp  
/bin/chown root:root /var/spool/at  
/bin/chown root:root /var/spool/cron  
/bin/chown root:root /var/spool/cron/root  
/bin/chown root:root /var/yp/binding  
